In [1]:
import pandas as pd
import numpy as np

## EDA

In [2]:
# import the dataset
dataset_df = pd.read_csv('dataset (1).csv')

In [3]:
dataset_df.head()

,Disease,Symptom_0,Symptom_1,Symptom_2,Symptom_3,Symptom_4,Symptom_5,Symptom_6,Symptom_7,Symptom_8,Symptom_9,Symptom_10,Symptom_11,Symptom_12,Symptom_13,Symptom_14,Symptom_15,Symptom_16
0,AIDS,muscle_wasting,patches_in_throat,high_fever,extra_marital_contacts,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,AIDS,patches_in_throat,high_fever,extra_marital_contacts,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,AIDS,muscle_wasting,high_fever,extra_marital_contacts,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,AIDS,muscle_wasting,patches_in_throat,extra_marital_contacts,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,AIDS,muscle_wasting,patches_in_throat,high_fever,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

There are 4930 patients

In [4]:
dataset_df.shape

(313, 18)

In [5]:
dataset_df = dataset_df.apply(lambda col: col.str.strip())

In [6]:
test = pd.get_dummies(dataset_df.filter(regex='Symptom'), prefix='', prefix_sep='')

In [7]:
test.head()

,acidity,back_pain,bladder_discomfort,breathlessness,burning_micturition,chest_pain,chills,constipation,continuous_sneezing,cough,...,congestion,phlegm,red_spots_over_body,blood_in_sputum,chest_pain,loss_of_smell,blood_in_sputum,loss_of_smell,muscle_pain,muscle_pain
0,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False

In [8]:
test = test.groupby(test.columns, axis=1).agg(np.max)

C:\Users\agarw\AppData\Local\Temp\ipykernel_12032\3730348491.py:1: FutureWarning: DataFrame.groupby with axis=1 is deprecated. Do `frame.T.groupby(...)` without axis instead.
  test = test.groupby(test.columns, axis=1).agg(np.max)
C:\Users\agarw\AppData\Local\Temp\ipykernel_12032\3730348491.py:1: FutureWarning: The provided callable <function max at 0x000001F5D6367740> is currently using DataFrameGroupBy.max. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "max" instead.
  test = test.groupby(test.columns, axis=1).agg(np.max)

In [9]:
clean_df = pd.merge(test,dataset_df['Disease'], left_index=True, right_index=True)

In [10]:
clean_df

,abdominal_pain,abnormal_menstruation,acidity,acute_liver_failure,altered_sensorium,anxiety,back_pain,belly_pain,blackheads,bladder_discomfort,...,watering_from_eyes,weakness_in_limbs,weakness_of_one_body_side,weight_gain,weight_loss,yellow_crust_ooze,yellow_urine,yellowing_of_eyes,yellowish_skin,Disease
0,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,AIDS
1,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,AIDS
2,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,AIDS
3,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,AIDS
4,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,AIDS
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
308,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,Varicose veins
309,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,Varicose veins
310,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,Varicose veins
311,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,Varicose veins
312,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,Varicose veins

In [11]:
clean_df.columns.get_loc('acidity')

2

In [12]:
test = np.zeros((1,132))

In [13]:
test[0,12]

0.0

Machine learning model: XGBoost random forest classifier

In [14]:
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
from sklearn.ensemble import GradientBoostingClassifier
from sklearn import preprocessing

In [15]:
X_data = clean_df.iloc[:,:-1]
y_data = clean_df.iloc[:,-1]

# Convert y to categorical values
y_data = y_data.astype('category')

In [16]:
X_data.shape

(313, 133)

In [17]:
y_data.shape

(313,)

In [18]:
le = preprocessing.LabelEncoder()
le.fit(y_data)

LabelEncoder()

In [19]:
y_data.cat.categories

Index(['AIDS', 'Acne', 'Alcoholic hepatitis', 'Allergy', 'Arthritis',
       'Bronchial Asthma', 'Cervical spondylosis', 'Chicken pox',
       'Chronic cholestasis', 'Common Cold', 'Covid', 'Dengue', 'Diabetes',
       'Dimorphic hemorrhoids(piles)', 'Drug Reaction', 'Fungal infection',
       'GERD', 'Gastroenteritis', 'Heart attack', 'Hepatitis A', 'Hepatitis B',
       'Hepatitis C', 'Hepatitis D', 'Hepatitis E', 'Hypertension',
       'Hyperthyroidism', 'Hypoglycemia', 'Hypothyroidism', 'Impetigo',
       'Jaundice', 'Malaria', 'Migraine', 'Osteoarthritis',
       'Paralysis (brain hemorrhage)', 'Paroxysmal Positional Vertigo',
       'Peptic ulcer disease', 'Pneumonia', 'Psoriasis', 'Tuberculosis',
       'Typhoid', 'Urinary tract infection', 'Varicose veins'],
      dtype='object')

In [20]:
X_train, X_test, y_train, y_test = train_test_split(X_data, y_data, test_size=0.2)

In [21]:
X_train.shape

(250, 133)

In [22]:
X_test.shape

(63, 133)

In [23]:
# Convert labels to numbers
y_train = le.transform(y_train)
y_test = le.transform(y_test)

In [ ]:
import xgboost as xgb

# Init classifier
model = xgb.XGBClassifier()

# Fit
model.fit(X_train, y_train)

# Predict
preds = model.predict(X_test)

In [25]:
le.inverse_transform(model.predict(X_test.iloc[1,:].to_numpy().reshape(1,-1)))

array(['Common Cold'], dtype=object)

In [26]:
y_data.cat.categories[1]

'Acne'

In [27]:
model.predict(X_test.iloc[2,:].to_numpy().reshape(1,-1))

array([10], dtype=int64)

In [28]:
model.predict_proba(X_test.iloc[2,:].to_numpy().reshape(1,-1))[0,15]

0.0006906497

In [29]:
accuracy_score(y_test, preds)

0.873015873015873

In [30]:
y_test

array([ 1,  9, 10, 23, 23, 36, 37, 38, 21,  8,  2,  6, 25, 24, 20, 27, 28,
       14, 22, 19, 27,  7, 38, 23, 29, 35,  2, 22, 31,  8, 35,  4, 30, 40,
       39, 38, 29, 35, 26, 25, 27, 16, 36, 41, 12,  6,  3, 26, 11, 41,  0,
       37, 36, 31,  0, 10, 18, 36, 31, 24,  5, 14,  7])

In [31]:
print(classification_report(y_test, preds))

              precision    recall  f1-score   support

           0       0.67      1.00      0.80         2
           1       1.00      1.00      1.00         1
           2       1.00      1.00      1.00         2
           3       1.00      1.00      1.00         1
           4       0.50      1.00      0.67         1
           5       1.00      1.00      1.00         1
           6       1.00      0.50      0.67         2
           7       1.00      1.00      1.00         2
           8       0.67      1.00      0.80         2
           9       1.00      1.00      1.00         1
          10       1.00      1.00      1.00         2
          11       1.00      1.00      1.00         1
          12       1.00      1.00      1.00         1
          13       0.00      0.00      0.00         0
          14       1.00      0.50      0.67         2
          15       0.00      0.00      0.00         0
          16       1.00      1.00      1.00         1
          18       0.00      0.00      0.00         1
          19       1.00      1.00      1.00         1
          20       1.00      1.00      1.00         1
          21       1.00      1.00      1.00         1
          22       1.00      0.50      0.67         2
          23       1.00      1.00      1.00         3
          24       0.50      1.00      0.67         2
          25       1.00      1.00      1.00         2
          26       1.00      1.00      1.00         2
          27       1.00      1.00      1.00         3
          28       0.00      0.00      0.00         1
          29       1.00      1.00      1.00         2
          30       1.00      1.00      1.00         1
          31       1.00      0.67      0.80         3
          32       0.00      0.00      0.00         0
          35       1.00      1.00      1.00         3
          36       1.00      1.00      1.00         4
          37       1.00      0.50      0.67         2
          38       1.00      1.00      1.00         3
          39       1.00      1.00      1.00         1
          40       0.00      0.00      0.00         1
          41       1.00      1.00      1.00         2

    accuracy                           0.87        63
   macro avg       0.80      0.79      0.78        63
weighted avg       0.91      0.87      0.87        63

C:\Users\agarw\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\metrics\_classification.py:1471: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\agarw\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\metrics\_classification.py:1471: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\agarw\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\metrics\_classification.py:1471: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\agarw\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\metrics\_classification.py:1471: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\agarw\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\metrics\_classification.py:1471: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\agarw\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\metrics\_classification.py:1471: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

In [32]:
y_train.cat.categories

AttributeError: 'numpy.ndarray' object has no attribute 'cat'

In [ ]:
y_train.cat.categories.

In [ ]:
y_train.cat.categories.to_list()

In [ ]:
# import the dataset
desc_df = pd.read_csv('../data/symptom_Description.csv')

In [ ]:
desc_df[desc_df['Disease'] == 'Malaria']['Description'].values[0]

In [ ]:
prec_df = pd.read_csv('../data/symptom_precaution.csv')

In [ ]:
prec_df[prec_df['Disease'] == 'Malaria'].filter(regex='Precaution').values.tolist()[0]

In [ ]:
pd.read_csv('../data/clean_dataset.tsv', sep='\t')